# Configures the travis continueous build.

language: R
sudo: required
# TODO(Jean): Set warnings_are_errors to false after document line length fixed.
warnings_are_errors: false

r_packages:
  - roxygen2

after_failure: "cat /home/travis/build/jeanimal/heuristica/heuristica.Rcheck/00check.log"
